//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanXeMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int MaCTHD { get; set; }
        public Nullable<int> MaHD { get; set; }
        public Nullable<int> MaCTXM { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string HoTen { get; set; }
        public string CanCuoc { get; set; }
        public string DienThoai { get; set; }
        public string SoKhung { get; set; }
        public string SoMay { get; set; }
        public string MauSac { get; set; }
        public string TenXe { get; set; }
        public string HangXe { get; set; }
    
        public virtual ChiTietXeMay ChiTietXeMay { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
