//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanXeMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeMay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XeMay()
        {
            this.ChiTietXeMays = new HashSet<ChiTietXeMay>();
        }
    
        public int MaXe { get; set; }
        public string TenXe { get; set; }
        public string HangXe { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MauSac { get; set; }
        public string SoKhung { get; set; }
        public string SoMay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietXeMay> ChiTietXeMays { get; set; }
    }
}
